services:
    nuxt:
        build: .
        ports:
            - "8455:3000"
        env_file:
            - .env
        volumes:
            - ./data:/app/data
            - ./public/episode-status.json:/app/public/episode-status.json
        restart: unless-stopped
